apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          # image: us.gcr.io/tickethub-dev-399117/tickets
          image: meghakhangarot17/tickets
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
          - name: NATS_CLIENT_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'http://nats-srv:4222'
          - name: NATS_CLUSTER_ID
            value: tickethub
          - name: MONGO_URI
            value: 'mongodb://tickets-mongo-srv:27017/tickets'
          - name: JWT_KEY
            valueFrom: 
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
spec:
  selector:
    app: tickets
  ports:
  - name: tickets
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
stringData:
  JWT_KEY: abcdef

